"use client";

import { motion } from "framer-motion";
import { ArrowLeft, Coins, Clock, Lock, Scale } from "lucide-react";
import Link from "next/link";

export default function InvToken() {
  return (
    <div className="min-h-screen bg-[#050505] text-white font-sans selection:bg-[#00FFC2] selection:text-black">
      <Nav />
      
      <main className="max-w-4xl mx-auto pt-32 pb-24 px-6">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-16"
        >
          <div className="flex items-center space-x-2 font-mono text-[#00FFC2] text-xs mb-4">
            <span className="bg-[#00FFC2]/10 px-2 py-1 rounded">ECONOMIC PRIMITIVE</span>
            <span className="text-white/40">//</span>
            <span>TESTNET V1</span>
          </div>
          <h1 className="text-5xl md:text-6xl font-serif mb-6">Universal Basic Share</h1>
          <p className="text-xl text-white/60 font-light leading-relaxed max-w-2xl">
            Identity is not a badge. It is verifiable work over time. <br/>
            The <strong>INV</strong> token quantifies the thermodynamic cost of maintaining a distinct human presence in a digital network.
          </p>
        </motion.div>

        <div className="grid md:grid-cols-2 gap-8 mb-16">
          <Card 
            icon={<Clock className="text-[#00FFC2]" />}
            title="Proof of Latency"
            desc="INV is minted based on time. 1.000000000000000000 unit represents exactly 24 hours of verified hardware continuity."
          />
          <Card 
            icon={<Lock className="text-[#00FFC2]" />}
            title="Soulbound (Testnet)"
            desc="INV_t cannot be bought, sold, or transferred. It stays in the wallet generated by your hardware. It measures loyalty, not liquidity."
          />
          <Card 
            icon={<Coins className="text-[#00FFC2]" />}
            title="The Genesis Pot"
            desc="5% of the future Mainnet supply is reserved for the Genesis Cohort. Your Testnet INV_t balance determines your weight in this allocation."
          />
          <Card 
            icon={<Scale className="text-[#00FFC2]" />}
            title="Sybil-Resistance"
            desc="To forge INV, an attacker must buy physical hardware. The Cost of Forgery > Profit from Corruption."
          />
        </div>

        <div className="prose prose-invert prose-p:font-light prose-p:text-white/80 border-t border-white/10 pt-12">
          <h3 className="font-serif text-3xl mb-6">The "Work" of Being Human</h3>
          <p>
            In Proof-of-Work, miners burn electricity to secure a ledger. In Invariant, nodes "burn" <strong>latency and hardware availability</strong> to secure the identity graph.
          </p>
          <p>
            By keeping your node active, you provide a "Heartbeat" to the network. This heartbeat creates a high-trust region in the graph, making it mathematically impossible for botnets to infiltrate without incurring massive physical costs.
          </p>
          <blockquote className="border-l-2 border-[#00FFC2] pl-6 italic text-white/60 my-8">
            "We do not pay you to use the app. We reward you for anchoring the truth."
          </blockquote>
        </div>
      </main>
    </div>
  );
}

function Nav() {
  return (
    <nav className="fixed top-0 w-full bg-[#050505]/80 backdrop-blur-md border-b border-white/10 z-50 px-6 h-16 flex items-center">
      <Link href="/" className="flex items-center space-x-2 text-white/60 hover:text-white transition-colors">
        <ArrowLeft size={18} />
        <span className="text-sm font-mono">RETURN</span>
      </Link>
    </nav>
  );
}

function Card({ icon, title, desc }: any) {
  return (
    <div className="bg-white/5 border border-white/10 p-6 rounded-lg hover:border-[#00FFC2]/50 transition-colors">
      <div className="mb-4">{icon}</div>
      <h3 className="text-xl font-serif mb-2">{title}</h3>
      <p className="text-sm text-white/60 font-light">{desc}</p>
    </div>
  );
}