/*
 * Copyright (c) 2026 Invariant Protocol.
 * Use of this software is governed by the MIT License.
 */

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use utoipa::ToSchema;

/// A cryptographic signal proving the continued existence of an entity.
///
/// This implements the "Secure Tap" protocol:
/// 1. Client requests Challenge (Nonce).
/// 2. Device signs Challenge inside TEE.
/// 3. Server validates Signature + Nonce Freshness.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct Heartbeat {
    /// The ID of the identity broadcasting this signal.
    pub identity_id: Uuid,

    /// The cryptographic signature generated by the hardware Secure Enclave.
    /// Signs: (identity_id || nonce || timestamp)
    pub device_signature: Vec<u8>,

    /// The server-issued challenge (preventing replay attacks).
    pub nonce: Vec<u8>,

    /// TrustedTime timestamp (checked for skew).
    pub timestamp: DateTime<Utc>,
}