/*
 * Copyright (c) 2025 Invariant Protocol
 * * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 */

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

/// A cryptographic signal proving the continued existence of an entity.
///
/// This struct acts as the "mining" unit for the Proof of Persistence protocol.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Heartbeat {
    /// The ID of the identity broadcasting this signal.
    pub identity_id: Uuid,

    /// The cryptographic signature generated by the hardware Secure Enclave.
    /// This asserts that the device key was present and active.
    pub device_signature: Vec<u8>,

    /// The timestamp when the signal was generated (TrustedTime).
    pub timestamp: DateTime<Utc>,
}