/*
 * Copyright (c) 2025 Invariant Protocol
 * Use of this software is governed by the Business Source License.
 */

use p256::ecdsa::{Signature, VerifyingKey, signature::Verifier};
use p256::pkcs8::DecodePublicKey;
use crate::error::EngineError;

/// Verifies a signature generated by Android Keystore (P-256).
pub fn verify_signature(
    public_key_bytes: &[u8],
    payload: &[u8],
    signature_bytes: &[u8]
) -> Result<(), EngineError> {
    // 1. Parse Public Key
    // Try parsing as DER (SPKI) first, which is standard for Android.
    let verifying_key = VerifyingKey::from_public_key_der(public_key_bytes)
        .or_else(|_| VerifyingKey::from_sec1_bytes(public_key_bytes)) // Fallback to raw bytes
        .map_err(|_| EngineError::InvalidSignature)?;

    // 2. Parse Signature
    // Android returns ASN.1 DER signatures.
    let signature = Signature::from_der(signature_bytes)
        .map_err(|_| EngineError::InvalidSignature)?;

    // 3. Verify
    verifying_key.verify(payload, &signature)
        .map_err(|_| EngineError::InvalidSignature)
}